.Dd February 28, 2011
.Dt IMAPFILTER 1
.Os
.Sh NAME
.Nm imapfilter
.Nd mail filter
.Sh SYNOPSIS
.Nm
.Op Fl Vdiv
.Op Fl c Ar configfile
.Op Fl e Ar 'command'
.Op Fl l Ar logfile
.Sh DESCRIPTION
.Nm
is a mail filtering utility.  It connects to remote mail servers using the
Internet Message Access Protocol (IMAP), sends searching queries to the server
and processes mailboxes based on the results.  It can be used to delete, copy,
move, flag, etc.  messages residing in mailboxes at the same or different mail
servers.  The 4rev1 and 4 versions of the IMAP protocol are supported.
.Pp
The command line options of
.Xr imapfilter 1
are as follows:
.Bl -tag -width Ds
.It Fl V
Displays program's version.
.It Fl c Ar configfile
Path to the configuration file.  The default is
.Pa $HOME/.imapfilter/config.lua .
.It Fl d
Debug mode; creates a temporary file name in
.Pa $HOME/.imapfilter/debug.XXXXXX ,
where debugging messages about the program's progress are printed.
.It Fl e Ar 'command'
May be used to enter one line of program (configuration).
When this options is used,
.Nm
will not look for any configuration file.
.It Fl i
Enters interactive mode after executing the configuration file or the command
line.
.It Fl l Ar logfile
File that contains logs of error messages
.Nm
produces.
.It Fl v
Verbose mode; prints detailed information about the program's actions.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev HOME
User's home directory.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa $HOME/.imapfilter/config.lua
Default configuration file.  Because this file may contain sensitive data such
as user passwords, the recommended permissions are read/write for the user, and
not accessible by others.
.It Pa $HOME/.imapfilter/certificates
File where the SSL/TLS certificates are stored.
.It Pa $HOME/.imapfilter/debug.XXXXXX
Debug files.
.El
.Sh SEE ALSO
.Xr imapfilter_config 5
.Sh CONFORMING TO
.Bl -tag -width Ds
.It IMAP4rev1:
RFC 3501, RFC 3348, RFC 2683, RFC 2595, RFC 2342, RFC 2195,
RFC 2177
.It IMAP4:
RFC 1730
.El
