---
name: docker

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
    branches:
      - '*'
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          # Spurious segfaults when compiling
          # https://github.com/docker/setup-qemu-action/issues/188
          image: tonistiigi/binfmt:qemu-v8.1.5
      - uses: docker/setup-buildx-action@v3

      - uses: docker/metadata-action@v5
        id: meta
        with:
          flavor: |
            latest=false
          images: |
            name=ghcr.io/${{ github.repository }},enable=${{ github.repository == 'lefcha/imapfilter' }} # publishing to ghcr.io/lefcha/imapfilter
            name=ghcr.io/${{ github.actor }}/imapfilter,enable=true # publish to the (PR) author's packages
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }} # set latest tag for releases
            type=semver,pattern={{raw}} # uses git tag as image tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
